/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthPage: typeof import('./src/components/AuthPage.vue')['default']
    BankChoosen: typeof import('./src/components/BankChoosen.vue')['default']
    BigAmount: typeof import('./src/components/BigAmount.vue')['default']
    CustomDatePicker: typeof import('./src/components/CustomDatePicker.vue')['default']
    DataAccept: typeof import('./src/components/DataAccept.vue')['default']
    DocumentRequired: typeof import('./src/components/DocumentRequired.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ModalCourier: typeof import('./src/components/ModalCourier.vue')['default']
    OrderList: typeof import('./src/components/OrderList.vue')['default']
    Packages: typeof import('./src/components/Packages.vue')['default']
    Registration: typeof import('./src/components/Registration.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
    Withdraw: typeof import('./src/components/Withdraw.vue')['default']
    WithdrawSuccess: typeof import('./src/components/WithdrawSuccess.vue')['default']
  }
}
